-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 14:12:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lista_tareas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lista_tareas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lista_tareas` DEFAULT CHARACTER SET utf8 ;
USE `lista_tareas` ;

-- -----------------------------------------------------
-- Table `lista_tareas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`categoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `orden` INT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_tareas`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`departamentos` (
  `id` BIGINT(19) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamentos_nombre_unique` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `lista_tareas`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`municipios` (
  `id` BIGINT(19) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `departamento_id` BIGINT(19) UNSIGNED NOT NULL,
  `acortado` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `municipios_nombre_index` (`nombre` ASC) VISIBLE,
  INDEX `municipios_departamento_id_index` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `municipios_departamento_id_foreign`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `lista_tareas`.`departamentos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 99774
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `lista_tareas`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`subcategoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategoria_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `lista_tareas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_tareas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`usuarios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `tipo_documento` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `documento` BIGINT(19) UNSIGNED NOT NULL,
  `telefono` BIGINT(19) UNSIGNED NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `municipio_id` BIGINT(19) UNSIGNED NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `user` VARCHAR(30) NULL DEFAULT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  `foto` VARCHAR(80) NULL DEFAULT NULL,
  `rol` ENUM('Administrador', 'Empleado', 'Cliente', 'Proveedor') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) VISIBLE,
  INDEX `fk_usuarios_municipios1_idx` (`municipio_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_municipios1`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `lista_tareas`.`municipios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `lista_tareas`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`tareas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha` DATETIME NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `usuarios_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tareas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_tareas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `lista_tareas`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_tareas`.`tareas_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`tareas_has_categoria` (
  `tareas_id` INT UNSIGNED NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  INDEX `fk_tareas_has_categoria_tareas1_idx` (`tareas_id` ASC) VISIBLE,
  INDEX `fk_tareas_has_categoria_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tareas_has_categoria_tareas1`
    FOREIGN KEY (`tareas_id`)
    REFERENCES `lista_tareas`.`tareas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_has_categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `lista_tareas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
