-- MySQL Script generated by MySQL Workbench
-- Sat Feb 19 16:35:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lista_tareas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lista_tareas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lista_tareas` DEFAULT CHARACTER SET utf8 ;
USE `lista_tareas` ;

-- -----------------------------------------------------
-- Table `lista_tareas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`categoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `orden` INT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_tareas`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`subcategoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategoria_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `lista_tareas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_tareas`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`tareas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha` DATETIME NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_tareas`.`tareas_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas`.`tareas_has_categoria` (
  `tareas_id` INT UNSIGNED NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  INDEX `fk_tareas_has_categoria_tareas1_idx` (`tareas_id` ASC) VISIBLE,
  INDEX `fk_tareas_has_categoria_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tareas_has_categoria_tareas1`
    FOREIGN KEY (`tareas_id`)
    REFERENCES `lista_tareas`.`tareas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_has_categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `lista_tareas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
